modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker_url}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="${mod_update_json_url}"
displayURL="${mod_homepage_url}"
logoFile="${mod_id}.png"
credits="${mod_credits}"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.smoothterrain]]
modId="neoforge"
mandatory=true
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.smoothterrain]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
